# VirtualTreeView appveyor.yml script

branches:
  only:
    - master

version: '{branch}-{build}'

os: Visual Studio 2022

before_build:
  nuget restore

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

configuration: Release

build:
  parallel: true
  publish_nuget: true
  publish_nuget_symbols: false

deploy:
  provider: NuGet
  api_key:
    secure: FXdfurOFdTV/iNGNBf9Vqb3teeqGMrwuMxpoWQMVzHsZ9roqoCCGOQxrzhRM5Wwm
