# VirtualTreeView appveyor.yml script

branches:
  only:
    - master

version: '{branch}-{build}'

os: Visual Studio 2022

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

configuration: Release
platform: Any CPU

build:
  parallel: false
  publish_nuget: true
  publish_nuget_symbols: true

deploy:
  provider: NuGet
  api_key:
    secure: Doc+VNHcVOc8oefVdQREqF1r4CoHBDd0Z/pj/HrnzMIndQecIq6BzPmyOMj2yJYE
  skip_symbols: false
